const TRANSACTION_TYPES = {
    JOB_POST: 'JobPost',
    ACCOUNT_REGISTRATION: 'AccountRegistration',
    UPGRADE_EMPLOYER: 'UpgradeEmployer'
};

const TRANSACTION_TYPE_VALUES = Object.values(TRANSACTION_TYPES);

const TRANSACTION_STATUSES = {
    PENDING: 'Pending',
    SUCCESS: 'Success',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled'
};

const TRANSACTION_STATUS_VALUES = Object.values(TRANSACTION_STATUSES);

const PAYMENT_METHODS = {
    MOMO: 'MoMo'
};

const MOMO_RESULT_CODES = {
    SUCCESS: 0
};

module.exports = {
    TRANSACTION_TYPES,
    TRANSACTION_TYPE_VALUES,
    TRANSACTION_STATUSES,
    TRANSACTION_STATUS_VALUES,
    PAYMENT_METHODS,
    MOMO_RESULT_CODES
};
